#!/bin/bash

if [ "$#" = 0 ];
then
    # softwareupdate -i -a
    echo "softwareupdate -i -a"
elif [ "$1" = "list" ];
then
    if [ "$#" -ne 1 ];
    then
        echo "Command list expected no arguments, got $(($#-1))"
    else
        # softwareupdate -l
        echo "softwareupdate -l"
    fi
elif [ "$1" = "install" ];
then
    if [ "$#" -ne 2 ];
    then
        echo "Command install expected 1 argument, got $(($#-1))"
    else
        # softwareupdate -i "$2"
        echo "softwareupdate -i $2"
    fi
elif [ "$1" = "download" ];
then
    if [ "$#" -ne 2 ];
    then
        echo "Command download expected 1 argument, got $(($#-1))"
    else
        # softwareupdate -d "$2"
        echo "softwareupdate -d $2"
    fi
elif [ "$1" = "-h" ];
then
    echo "Usage: macosupdate [<COMMAND>] [<OPTION>]"
    echo "[<COMMAND>]:"
    echo "  list"
    echo "  install <NAME>"
    echo "  download <NAME>"
else
    echo "Command $1 is not a valid command."
    echo "Usage: macosupdate [<COMMAND>] [<OPTION>]"
    echo "[<COMMAND>]:"
    echo "  list"
    echo "  install <NAME>"
    echo "  download <NAME>"
fi
